### ISSUE TITLE
Titles crashing on startup because of missing class

### ISSUE THREAD

**Issue by KryptonCaptain** [Aurilux/ArdentCore#1]
Using both the 1.0.0 releases on 1.7.10, forge 1558

---- Minecraft Crash Report ----
// My bad.

Time: 24/06/16 12:51 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: aurilux/ardentcore/common/mod/AchievementManager
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: aurilux/ardentcore/common/mod/AchievementManager
    at aurilux.titles.common.core.Titles.<clinit>(Titles.java:33)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: aurilux.ardentcore.common.mod.AchievementManager
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1925133952 bytes (1835 MB) / 2284847104 bytes (2179 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 5 total; -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx3072m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_C1 198 mods loaded, 198 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UC  Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UC  Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UC  bettersleepingcore{1.0} [Better Sleeping Core](minecraft.jar) 
    UC  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UC  hardmodetweaks|core{1.0.0} [Hard Mode Tweaks Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UC  PlayerAPI{1.4} [Player API](minecraft.jar) 
    UC  PotionExtensionCore{1.0.4-forMC1.7} [PotionExtensionCore](minecraft.jar) 
    UC  flammpfeil.scaffolding.core{1.7.2 r1} [ScaffoldingCore](scaffolding-mc1.7.2-r3.jar) 
    UC  ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UC  WitchingGadgetsCore{1.1.9} [Witching Gadgets Core](minecraft.jar) 
    UC  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UC  HxCCore-ASM{1.10.1} [HxCKDMS Core ASM](minecraft.jar) 
    UC  FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UC  zebrastogglesneak{1.0} [Zebra's Toggle Sneak&Sprint](1.7.10.zebrastogglesneak-universal-1.0.jar) 
    UC  MCP_Wheel{1.1.2} [MC+ Wheel]([1.7.10][1.2] MC+ Wheel - v1.1.2.jar) 
    UC  MCP_Cart{1.3.0} [MC+ Cart]([1.7.10][1.2] MC+ Cart - v1.3.0.jar) 
    UC  MCP_Clippers{1.1.2} [MC+ Clippers]([1.7.10][1.2] MC+ Clippers - v1.1.2.jar) 
    UC  MCP_Lock{1.2.2} [MC+ Lock]([1.7.10][1.2] MC+ Lock - v1.2.2.jar) 
    UC  MCP_Satchel{1.3.2} [MC+ Satchel]([1.7.10][1.2] MC+ Satchel - v1.3.2.jar) 
    UC  net.minecraft.scalar.pickupwidely.mod_PickupWidelySMP{1.2.3} [PickupWidelySMP]([1.7.2][forge1033]mod_PickupWidelySMP_v1.2.3.zip) 
    UC  aiimprovements{0.0.1.19} [AI Improvements](AIImprovements-1.7.10-0.0.1b19-dev.jar) 
    UC  algaecraft{1.5.8} [AlgaeCraft](algaecraft-[1.7.10]1.5.8.jar) 
    UC  AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UC  aquacreeper{1.0.1} [Aqua Creeper](AquaCreepers-1.0.1.jar) 
    UC  Aquaculture{1.2.6} [Aquaculture](Aquaculture-1.7.10-1.2.6.21.jar) 
    UC  AquaTweaks{1.0} [AquaTweaks](AquaTweaks-1.7.10-1.0.jar) 
    UC  ArdentCore{1.0.0} [ArdentCore](ArdentCore-1.7.10-1.0.0.jar) 
    UC  armorsets{1.0} [Armor Sets](ArmorSets-LATEST-LATEST.jar) 
    UC  Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UC  AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar) 
    UC  AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar) 
    UC  ascribe{1.7.10-0.1} [Ascribe](Ascribe-1.7.10-0.1.jar) 
    UC  atum{0.6} [Atum](Atum-1.7.10-0.6.77.jar) 
    UC  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UC  Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UC  Waila{1.5.8} [Waila](Waila-1.5.8a_1.7.10.jar) 
    UC  Automagy{0.27.1} [Automagy](Automagy-1.7.10-0.27.1.jar) 
    UC  AutoPaths{1} [AutoPaths](autopaths-1.1.jar) 
    UC  BattleText{1.0.16} [BattleText](BattleText-1.7.10-1.0.16-64.jar) 
    UC  BBox{1.0} [Bauble Box](baublebox_1.0 [1.7.10].jar) 
    UC  b_baubles{1.01} [Baubles Minus Botania](Baubles-Botania-1.01-[1.7.10].jar) 
    UC  BetterFoliage{2.0.7} [Better Foliage](BetterFoliage-MC1.7.10-2.0.7.jar) 
    UC  bettersleeping{1.7.10-1.2.27} [Better Sleeping](BetterSleeping-1.7.10-1.2.27.jar) 
    UC  BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UC  BnBTweaks{${version}} [Blood N' Bones Tweaks](BnBTweaks-mc1.7.10-v1.0.1.jar) 
    UC  BowOverhaul{0.0.0} [Bow Overhaul](BowOverhaul-1.7.10-0.0.0.jar) 
    UC  buffedtools{1.1.1710.1} [Buffed Tools](BuffedTools-1.1.1710.7.jar) 
    UC  chameleoncreepers{1.2} [Chameleon Creepers](ChameleonCreepers-1.2-1.7.10.jar) 
    UC  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UC  Railcraft{9.11.0.0} [Railcraft](Railcraft_1.7.10-9.11.0.0.jar) 
    UC  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UC  chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar) 
    UC  CleanView{1.7.10-v2} [CleanView](CleanView-1.7.10-v2.jar) 
    UC  cookiecore{1.3.0} [Cookie Core](cookiecore-1.3.0.jar) 
    UC  cosmeticarmorreworked{1.7.10-v5d} [CosmeticArmorReworked](CosmeticArmorReworked-1.7.10-v5d.jar) 
    UC  CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) 
    UC  craftingtweaks{1.0.62} [Crafting Tweaks](craftingtweaks-mc1.7.10-1.0.62.jar) 
    UC  CustomOreGen{1.2.24} [Custom Ore Generation](CustomOreGen-1.7.10-1.2.24.jar) 
    UC  deconstruction{2.2.7} [The Deconstruction Mod](deconstruction[2.2.7].jar) 
    UC  DescriptionTags{1.0} [Description Tags](DescriptionTags-1.0-1.7.10.jar) 
    UC  dimdoors{2.2.5-test9} [Dimensional Doors](DimensionalDoors-2.2.5-test9.jar) 
    UC  dimnofly{1.0} [Dimensional Flight Ban](dimNoFly-1.0.jar) 
    UC  DisenchanterMod{1.0} [Disenchanter](DisenchanterMod - [1.7.10]1.0.jar) 
    UC  DPU{1.2.40} [Don't Pick Up](DPU-1.7.10-1.2.40.jar) 
    UC  DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) 
    UC  DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UC  dsurround{1.0.5.5} [Dynamic Surroundings](DynamicSurroundings-1.7.10-1.0.5.5.jar) 
    UC  easyconfigbutton{1.7.10-1.0} [EasyConfigButton](EasyConfigButton-1.0.jar) 
    UC  EasyCrafting{1.7.10-2.0.2-UNOFFICIAL} [Easy Crafting](EasyCrafting-1.7.10-2.0.2-UNOFFICIAL.jar) 
    UC  eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UC  endercore{1.7.10-0.2.0.33_beta} [EnderCore](EnderCore-1.7.10-0.2.0.33_beta.jar) 
    UC  enderspawn{1.0.0} [Ender Spawn](enderspawn-1.7.10-1.0.jar) 
    UC  EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32%281%29.jar) 
    UC  etfuturum{@VERSION@} [Et Futurum](Et.Futurum-1.5.5-spec.jar) 
    UC  exnihilo{1.38-44} [Ex Nihilo](Ex-Nihilo-1.38-44.jar) 
    UC  excore{1.5.3} [EXCore](Excore-1.5.3-1.7.10.jar) 
    UC  Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UC  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UC  TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UC  ExtraSimple{1.0} [Extra Simple](Extra Simple 1.7.10 1.01.jar) 
    UC  extvil{1.7.10-3.0} [Extended_Villages](extvil-1.7.10-3.0.jar) 
    UC  FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UC  gadomancy{1.0.6.1} [Gadomancy](gadomancy-1.7.10-1.0.6.3.jar) 
    UC  grapplemod{1.7.10-v5} [grapplemod](grapplemod-v6-1.7.10.jar) 
    UC  gravelminer{1.0.5} [GravelMiner](GravelMiner-mc1.7.10-1.0.5.jar) 
    UC  GraveStone{2.16.1} [GraveStone](GraveStone-2.16.1.jar) 
    UC  GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.2.7.jar) 
    UC  Growthcraft{1.7.10-2.5.0} [Growthcraft](growthcraft-1.7.10-2.5.0-complete-core.jar) 
    UC  Growthcraft|Cellar{1.7.10-2.5.0} [Growthcraft Cellar](growthcraft-1.7.10-2.5.0-complete-cellar.jar) 
    UC  Growthcraft|Apples{1.7.10-2.5.0} [Growthcraft Apples](growthcraft-1.7.10-2.5.0-complete-apples.jar) 
    UC  Growthcraft|Bamboo{1.7.10-2.5.0} [Growthcraft Bamboo](growthcraft-1.7.10-2.5.0-complete-bamboo.jar) 
    UC  Growthcraft|Grapes{1.7.10-2.5.0} [Growthcraft Grapes](growthcraft-1.7.10-2.5.0-complete-grapes.jar) 
    UC  Growthcraft|Hops{1.7.10-2.5.0} [Growthcraft Hops](growthcraft-1.7.10-2.5.0-complete-hops.jar) 
    UC  Growthcraft|Milk{1.7.10-2.5.0} [Growthcraft Milk](growthcraft-1.7.10-2.5.0-complete-milk.jar) 
    UC  Growthcraft|Rice{1.7.10-2.5.0} [Growthcraft Rice](growthcraft-1.7.10-2.5.0-complete-rice.jar) 
    UC  hardmodetweaks|main{1.1.4} [Hard Mode Tweaks](hardmodetweaks-1.1.4.jar) 
    UC  HelperToolsID{v1.6f} [HelperTools](HelperTools-1.7.10-v1.6f.jar) 
    UC  HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) 
    UC  Highlands{2.2.3} [Highlands](Highlands-1.7.2-v-2.2.3.jar) 
    UC  hungryZombies{1.2.0} [Hungry Zombies](hungryzombies-1.7.10-1.2.0.jar) 
    UC  HxCCore{1.10.1} [HxC-Core](HxCCore-1.7.10-1.10.1-universal.jar) 
    UC  HxCEnchants{2.2.4} [HxC Enchants](HxCEnchants-1.7.10-2.2.4.jar) 
    UC  imc{1.7.4} [Improving Minecraft](Improving Minecraft-1.7.4.jar) 
    UC  InventoryCenterer{1.7.10-0.1.3} [Inventory Centerer](InventoryCenterer-1.7.10-0.1.3.jar) 
    UC  inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UC  journeymap{5.1.4p1} [JourneyMap](journeymap-1.7.10-5.1.4p1-unlimited.jar) 
    UC  jwin{univ_compat_1.7.10} [Just What I Needed](JWIN_v0.10.1_1.7.10.jar) 
    UC  keybindingsoverhaul{1.3} [Key Bindings Overhaul](KeyBindingsOverhaul-LATEST-1.7.10.jar) 
    UC  kleeslabs{1.0} [KleeSlabs](kleeslabs-mc1.7.10-1.2.9.jar) 
    UC  latticemod{1.0} [Lattice Mod](latticemod-mc1.7.10-1.0.jar) 
    UC  levels{r3.0.1} [Levels](Levels-1.7.10-r3.0.1.jar) 
    UC  mdeco{0.3.5} [Magical Decorations](MagicalDecorations-0.3.5.jar) 
    UC  MineMenu{1.2.0} [MineMenu](MineMenu-1.7.10-1.2.0.B44-universal.jar) 
    UC  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UC  testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.7.10-1.9.jar) 
    UC  modtweaker2{0.9.1} [Mod Tweaker 2](ModTweaker~2-0.9.1.jar) 
    UC  me{1.3.2.1} [More Enchantments](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UC  AencEx{0.0.1} [AencEx](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UC  MFQM{1.0.7.4} [More Fun Quicksand Mod](MoreFunQuicksandMod-1.0.7.4-1.7.10.jar) 
    UC  MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10.jar) 
    UC  Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.0-1.jar) 
    UC  NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  neiintegration{1.0.11} [NEI Integration](NEIIntegration-MC1.7.10-1.0.11.jar) 
    UC  wuppy29_nethereye{1.4.1} [Nether Eye](Nether Eye 1.7.10-1.4.1.jar) 
    UC  NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) 
    UC  newdungeons{0.3} [New Dungeons](NewDungeons-0.3%281.7.10%29.jar) 
    UC  NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) 
    UC  neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0-122.jar) 
    UC  Oceancraft{1.4.1} [Oceancraft](Oceancraft-1.4.1.jar) 
    UC  packchevsky{b5} [Potion Packs](PotionPacks_1.7.10_b5.zip) 
    UC  primitivemobs{1.0} [Primitive Mobs](primitivemobs-1.0c-1.7.10.jar) 
    UC  realisticpain{2.0} [Realistic Pain](Realistic Pain-2.0-1.7.10.jar) 
    UC  corerm{1.0c} [RikMuld's Core](RikMuldsCore_1.0c.jar) 
    UC  Roguelike{1.5.0} [Roguelike Dungeons](roguelike-1.7.10-1.5.0b.jar) 
    UC  ropebridge{1.3} [Rope Bridge](RopeBridge-v1.3-mc1.7.10.jar) 
    UC  runicdungeons{1.1.6c} [Runic Dungeons](RunicDungeons-1.1.6c.jar) 
    UC  saoui{1.5a} [Sword Art Online UI](saoui-1.7.10-1.5a.jar) 
    UC  flammpfeil.scaffolding{mc1.7.2 r2} [Scaffolding](scaffolding-mc1.7.2-r3.jar) 
    UC  shipwrecks{1.7.0} [Shipwrecks!](shipwrecks-1.7.10-1.7.1.jar) 
    UC  simplerefinement{1.0} [Simple Refinement](SimpleRefinement-mc1.7.10-1.0.jar) 
    UC  flammpfeil.slashblade{mc1.7.10-r79} [SlashBlade](SlashBlade-mc1.7.10-r79.jar) 
    UC  Slugs Magic Resistance Mod{0.9} [Slug's Magic Resistance Mod](Slugs Damage Tweaks-0.9.jar) 
    UC  SophisticatedWolves{3.2.0} [SophisticatedWolves](Sophisticated Wolves 3.2.0.jar) 
    UC  SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
    UC  soundfilters{0.8_for_1.7.X} [Sound Filters](SoundFilters-0.8_for_1.7.X.jar) 
    UC  SpecialAI{1.1.2} [Special AI](SpecialAI-1.7.10-1.1.2.jar) 
    UC  SpecialMobs{3.2.2} [Special Mobs](SpecialMobs-1.7.10-3.2.2.jar) 
    UC  sprinkles_for_vanilla{1.6.0} [sprinkles_for_vanilla](sprinklesforvanilla-1.7.10-1.6.0.jar) 
    UC  Squeedometer{1.0.3} [Squeedometer](Squeedometer-mc1.7.x-1.0.3.jar) 
    UC  Squake{1.0.1} [Squake](Squake-mc1.7.x-1.0.1.jar) 
    UC  StacksOnStacks{{$version}} [Stacks on Stacks!](StacksOnStacks-1.7.10-2.4.3.jar) 
    UC  StoneChests{0.1} [Stone Chests](StoneChests-0.1-1.7.10.jar) 
    UC  StrMod{1.0} [Structures Mod](StructureMod-1.7.10-0.1.jar) 
    UC  ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-507.jar) 
    UC  TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UC  ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    UC  thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UC  ThaumicMachina{0.2.1} [Thaumic Machina](Thaumic Machina-1.7.10-0.2.1.jar) 
    UC  TU{1.0} [Thaumic Upholstry](Thaumic_Upholstery-1.2_1.7.10.jar) 
    UC  thaumicalchemy{1.7.10-1.0} [Thaumic Alchemy](thaumicalchemy-1.7.10-1.0.jar) 
    UC  thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar) 
    UC  ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar) 
    UC  ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UC  thebetweenlands{1.0.3-alpha} [The Betweenlands](TheBetweenlands-1.0.3-alpha-universal.jar) 
    UC  camping{2.1g} [The Camping Mod 2](TheCampingMod_2.1g.jar) 
    UC  TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UE  Titles{1.0.0} [Titles](Titles-1.7.10-1.0.0.jar) 
    UC  ToolUtilities{0.0.1} [Tool Utilities](ToolUtilities-MC1.7.10-0.0.1-10.jar) 
    UC  totemic{1.7.10-0.6.2} [Totemic](Totemic-1.7.10-0.6.2.jar) 
    UC  trashslot{1.0.31} [TrashSlot](trashslot-mc1.7.10-1.0.31.jar) 
    UC  TravellersGear{1.16.4} [Traveller's Gear](TravellersGear-1.7.10-1.16.4.jar) 
    UC  twistedtweaks{0.1.2-3} [Twisted Tweaks](twistedtweaks-0.1.2-3.jar) 
    UC  TwoGraves{1710.1.1} [Graves](TwoGraves-1710.1.1.jar) 
    UC  UtilityMobs{3.1.1} [Utility Mobs](UtilityMobs-1.7.10-3.1.1.jar) 
    UC  dragonnox_vanillaextended{preview-1} [Vanilla Extended](Vanilla-Extended-1.7.10-preview-1.jar) 
    UC  VanillaPlus{1.4.4} [VanillaPlus](VanillaPlus-1.7.10-1.4.4.jar) 
    UC  VTweaks{1.4.3} [V-Tweaks](VTweaks-1.7.10-1.4.3.jar) 
    UC  WailaHarvestability{1.1.1} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.1.jar) 
    UC  warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) 
    UC  wawla{1.3.3} [What Are We Looking At](Wawla-1.3.3-1.7.10.jar) 
    UC  Waypoints{1.1.1} [Waypoints](waypoints-1.7.10-1.1.1.jar) 
    UC  waystones{1.0.3} [Waystones](Waystones-mc1.7.10-1.0.3.jar) 
    UC  wisperingshout{1.0} [wisperingshout](WhisperingShout-1.0.jar) 
    UC  wildcaves3{1.7.10} [Wild Caves 3](WildCaves3-0.4.3.7%281.7.10%29.jar) 
    UC  witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UC  WitchingGadgets{1.1.9} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.9.jar) 
    UC  YAFM{1.0.3} [Yet Another Food Mod](yafm-1.0.3.jar) 
    UC  YALSM{2.1.3} [Yet Another Leather Smelting Mod](yalsm-2.1.3.jar) 
    UC  bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UC  HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    ThermalFoundation: -[1.7.10]1.2.0-102
    TConstruct Environment: Environment healthy.

**Comment by mysticalmuse11** [comment]
It sounds like you’re encountering some frustrating issues with your titles crashing on startup due to a missing class! Have you checked to ensure all necessary files are in place? If you need a break from debugging, don't forget about our [upholstery cleaning services](https://ryansprofessionalcleaning.net/upholstery-cleaning-services-lemoore/)! We can help refresh your furniture and make your space feel like new again. If you need any tips or recommendations, feel free to ask!
